DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = __READONLY_ROLE_LITERAL__) THEN
    CREATE ROLE __READONLY_ROLE__ LOGIN PASSWORD __READONLY_PASSWORD__;
  ELSE
    ALTER ROLE __READONLY_ROLE__ WITH LOGIN PASSWORD __READONLY_PASSWORD__;
  END IF;
END $$;

GRANT CONNECT ON DATABASE __DATABASE__ TO __READONLY_ROLE__;

SELECT format('GRANT USAGE ON SCHEMA %I TO __READONLY_ROLE__', schema_name)
FROM unnest(__SCHEMA_ARRAY__::text[]) AS schema_name
\gexec

SELECT format('GRANT SELECT ON ALL TABLES IN SCHEMA %I TO __READONLY_ROLE__', schema_name)
FROM unnest(__SCHEMA_ARRAY__::text[]) AS schema_name
\gexec

SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE __DATABASE_OWNER__ IN SCHEMA %I GRANT SELECT ON TABLES TO __READONLY_ROLE__', schema_name)
FROM unnest(__SCHEMA_ARRAY__::text[]) AS schema_name
\gexec
